version: '3.9'

services:
  front:
    image: '{{ env.IMAGE_URL }}'
    container_name: front
    environment:
      ENV_VARIABLE: '{{ env.ENV_VARIABLE }}'
      NEXT_PUBLIC_ENV_VARIABLE: '{{ env.NEXT_PUBLIC_ENV_VARIABLE }}'
      ANALYZE: '{{ env.ANALYZE }}'
      NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: '{{ env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID }}'
    restart: always
    # for domain connection
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`monopomnom.ru`)
      - traefik.http.middlewares.traefik-compress.compress=true
      - traefik.http.routers.traefik.middlewares=traefik-compress
      - traefik.http.services.front.loadbalancer.server.port=3000
  traefik:
    image: traefik:v2.8
    container_name: traefik
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.monopomnom.ru`)
      - traefik.http.middlewares.traefik-compress.compress=true
      - traefik.http.routers.traefik.middlewares=traefik-compress
      - traefik.http.routers.traefik.service=api@internal
