version: '3.9'

services:
  front:
    image: '{{ env.IMAGE_URL }}'
    container_name: front
    build:
      args:
        ENV_VARIABLE: '{{ env.ENV_VARIABLE }}'
        NEXT_PUBLIC_ENV_VARIABLE: '{{ env.NEXT_PUBLIC_ENV_VARIABLE }}'
    restart: always
    ports:
      - '3000:3000'
