version: '3.9'

services:
  front:
    image: next-starter
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      ANALYZE: ${ANALYZE}
      NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: ${NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID}
    volumes:
      - ./pages:/app/pages
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    # for domain connection
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`next-starter.localhost`)
      - traefik.http.services.front.loadbalancer.server.port=3000
  traefik:
    image: traefik:v2.8.4
    container_name: traefik
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`dash.localhost`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=auth
      # Note: all dollar signs in the hash need to be doubled for escaping.
      # Passwords must be hashed using BCrypt.
      - traefik.http.middlewares.auth.basicauth.users=master:$$2a$$12$$oHjf0vln2dmOInRNDhDML.eio9jBwfJmnAybMoT/Q10tIh10k0qeK
