FROM node:18-alpine

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json* ./
RUN npm ci

COPY src ./src
COPY pages ./pages
COPY public ./public
COPY next.config.js .
COPY tsconfig.json .

EXPOSE 3000

CMD npm run dev
