import type { ReactElement } from 'react'
import { NextSeo } from 'next-seo'
import type { NextPageWithLayout } from 'pages/_app'
import Layout from '@widgets/layout'
import HomePage from '@pages/home'

const Home: NextPageWithLayout = () => {
	return (
		<>
			<NextSeo
				title='Index page'
				description='Generated by create next app'
				openGraph={{
					title: 'Index page',
					description: 'Generated by create next app',
				}}
			/>

			<HomePage />
		</>
	)
}

Home.getLayout = function getLayout(page: ReactElement) {
	return <Layout>{page}</Layout>
}

export default Home
